### ISSUE TITLE
A question regarding the usage of wisecondor

### ISSUE THREAD

**Issue by JIAYUREN000** [VUmcCGP/wisecondor#30]
Hi,

Mr Straver, it's glad to meet you here. Recently, I successfully installed wisecondor on my linux computer and tried to run it using a test bam file (the command line used : python wisecondor.py convert /ifs5/BC_ONLINE_RD/BIGDATA/Nifty-Cancer/rawdata/rawfq/16B1220256/GS90003457-FS3-L07_12.bam /dataFiles/16B1220256.npz -binsize 50000). However, it reported a fatal error with respect to git (refer to the screen shot), would you please give some suggestion on solving this error? Thank you so much.
![default](https://cloud.githubusercontent.com/assets/26448223/23978330/66dc7b5c-0a2e-11e7-9717-8f63d0d08661.PNG)

Jia

**Comment by rstraver** [comment]
Hi, are you sure the issue is the Git part? It seems to complain about the path to the file at the very end, which appears to be an absolute path rather than a relative which seems to be what you want. This part in your command appears to need a dot:
`/dataFiles/16B1220256.npz` should be `./dataFiles/16B1220256.npz`

Let me know if that solves the issue.
