### ISSUE TITLE
create referece

### ISSUE THREAD

**Issue by chaizuolin** [VUmcCGP/wisecondor#34]
Hello ,I created the reference with 1000 samples. Why is it all gray regions. 
![image](https://user-images.githubusercontent.com/33504864/32589281-9adf4750-c54e-11e7-83c0-5bbf63f55a92.png)

**Comment by dridk** [comment]
Chromosom 13,14,15 and 21,22 are acrocentric . That means there are no DNA content in the short arm.  centromeric region are also gray without dna content.

**Comment by chaizuolin** [comment]
What I mean is. I created the reference with 1000 samples. Why are all chromosomes Unmappable region.
![image](https://user-images.githubusercontent.com/33504864/32595415-d917e060-c56a-11e7-94fc-1df32e129fcb.png)
but ,I created the reference with 700 samples ,come out 
![image](https://user-images.githubusercontent.com/33504864/32595612-8340b3aa-c56b-11e7-9bb0-0aa28b38e742.png)
Created the reference is  the more samples the better.How many samples are you recommended to create

**Comment by dvanbeek** [comment]
Hi chaizuolin,

I vaguely remember seeing such a plot before. If I remember correctly the reference in this case was build using the raw .pickle files instead of the GC-corrected ones (.gcc). Normally the flow of building a WISECONDOR reference is like this (also described in the wiki): 

1. .bam -> .pickle, using: 
`samtools rmdup -s sample.bam - | samtools view - -q 1 | python consam.py -outfile sample.pickle`
2. .pickle -> .gcc, using:
`python ./gcc.py ./in/sample.pickle ./ref/gccount ./in/sample.gcc` 
3. All .gcc files of the reference samples in one directory (in line below ./in/refs/) -> one new reference set file (in line below ./ref/reference), using:
`python newref.py ./in/refs/ ./ref/reference`

Could you double check if you indeed performed step 2?

**Comment by chaizuolin** [comment]
Good, Thank you very much. How many samples do you recommend to create the reference and how much data size is in each sample.

**Comment by dvanbeek** [comment]
Hi chaizuolin,

Did my previous comment solve your issue with the reference set of 1000 samples? 

Regarding your follow up question, please see [the wiki](https://github.com/VUmcCGP/wisecondor/wiki/Understanding-the-input), sections _What do I put in for reference data?_ and _How many reads do I need for analysis?_.

It seems to me that you are using the legacy version of WISECONDOR, did you also try the newest version (master)? The new version should allow you to look more closely at the signal of the samples (we've seen a higher resolution when using the new version). Because of your large number of samples, you should definitely see an improvement. 
Running WISECONDOR is slightly different when using the new version, please let me know if you need additional help.

**Comment by chaizuolin** [comment]
Hello. I see "How many reads do I need for analysis?" inside the wiki.
But I can't find " How many reads do I need for analysis?" The RETRO filter parameter mentioned in this article

**Comment by dvanbeek** [comment]
Hi chaizuolin,

You can find and set the parameters for the RETRO filter in the consam.py file: -retdist and -retthres. Default value of both parameters is 4. 
In the [Supplementary data of the WISECONDOR paper](http://nar.oxfordjournals.org/content/early/2013/10/28/nar.gkt992.short) you can read up on the way the RETRO filter works (and find details about the parameters). 

Did the information in this issue help solve your problem with the gray regions?
