### ISSUE TITLE
On new version wisecondor z-score threshold  problems

### ISSUE THREAD

**Issue by chaizuolin** [VUmcCGP/wisecondor#35]
hello:"The z-score threshold is now dependent on the amount of tests within a sample" ,I don't quite understand the meaning of this sentence. Can you explain it in more detail. thank you

**Comment by rstraver** [comment]
The statement refers to this piece of code:

```
	num_tests = sum(masked_sizes)
	z_threshold = norm.ppf(1 - 1. / (num_tests * 0.5 * args.multitest))

	if args.minzscore is not None:
		z_threshold = args.minzscore
```

Previously we simply assumed a z-score of 3 is fair, independent of the binsize and therefore the amount of tests applied in a sample. In the newer version, the amount of tests done increases significantly upon increasing the resolution, hence I felt it was needed to account for this. Rather than blindly going with a pre-set threshold, the total number of z-score tests applied in a sample is estimated and the z-score threshold is increased to reduce the number of false positives accordingly.
However, if you wish to, a predetermined threshold is still possible, as shown by the minzscore argument.

**Comment by bnouyou** [comment]
Hello,
I have a question regarding the z-score threshold. I understand this threshold is now dynamic. But where can we find the value of this threshold in the results files ?
Thank you in adavance for your answer.

**Comment by rstraver** [comment]
I believe that threshold should be in the .npz file created by the testing functionality:
`threshold_z`

Following the code written in `toolReport` I think you should be able to retrieve this value (loading a numpy file and accessing that specific value).

**Comment by bnouyou** [comment]
Thank you for your answer.
